version: '3.7'
services:
  ekubo:
    container_name: ekubo
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    #command: sh -c "pwd && yarn start"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true