version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
        name: build docker image
        command: docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web .
      - run:
        name: setup heroku command
        command: bash .circleci/setup_heroku.sh
      - run:
        name: heroku maintenance on
        command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
        name: push container to registry.heroku.com
        command: |
          docker login --username=${HEROKU_LOGIN} --password=${HROKU_AUTH_TOKEN} registry.heroku.com
          docker push registry.heroku.com/${HEROKU_APP_NAME}/web
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
      - run:
        name: heroku maintenance off
        command: heroku maintenance:off --app ${HEROKU_APP_NAME}

      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
workflows:
    build-and-test:
      jobs:
        - deploy:
          filters:
            branches:
              only: master