---
  jobs:
    build:
      machine:
        image: circleci/classic:edge
      # executor:
      #   name: node/default
      # docker:
      #- image: circleci/node:4.8.2
      steps:
        - checkout

        - run:
          name: docker-compose build
          command: docker-compose build

    deploy:
      machine:
        image: circleci/classic:edge
      steps:
        - checkout
        - run:
          command: "docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web ."
          name: "build docker image"
        - run:
          command: "bash .circleci/setup_heroku.sh"
          name: "setup heroku command"
        - run:
          command: "heroku maintenance:on --app ${HEROKU_APP_NAME}"
          name: "heroku maintenance on"
        - run:
          command: |
              docker login --username=${HEROKU_LOGIN} --password=${HROKU_AUTH_TOKEN} registry.heroku.com
              docker push registry.heroku.com/${HEROKU_APP_NAME}/web
              heroku container:push web --app ${HEROKU_APP_NAME}
              heroku container:release web --app ${HEROKU_APP_NAME}
          name: "push container to registry.heroku.com"
        - run:
          command: "heroku maintenance:off --app ${HEROKU_APP_NAME}"
          name: "heroku maintenance off"
        # - run:
        #   node/with-cache:
        #     steps:
        #       -
        #         run: "yarn install"
        #       -
        #         run: "yarn test"
  orbs:
    node: circleci/node@1.1.6
  version: 2.1
  workflows:
    build_and_deploy:
      jobs:
        - build:
          filters:
            branches:
              only: master
        - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
