version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout

      - run:
          name: docker-compose build
          command: docker-compose build

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout

      - run:
          name: "retrieve token"
          command: "aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_URI_VALUE}"

      # - run:
      #     name: "Build Docker image"
      #     command: "docker build -t ekubo ."

      - run:
          name: "Build Docker image"
          command: "docker-compose build "

      - run:
          name: "tag your image"
          command: "docker tag ekubo-prod:latest ${AWS_URI_VALUE}/ekubo:latest"

      - run:
          name: "push your image"
          command: "docker push ${AWS_URI_VALUE}/ekubo:latest"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
             - build
