version: 2
jobs:
  build:
    working_directory: ~/ekubo
    # machine: true
    docker:
      - image: circleci/node:stretch
    # executor:
    #   name: node/default
    # docker:
    #- image: circleci/node:4.8.2
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: docker-compose build
          command: docker-compose build

  deploy:
    working_directory: ~/ekubo
    # machine: true
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: "docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web ."
          name: "build docker image"
      - run:
          command: "bash .circleci/heroku_setup.sh"
          name: "setup heroku command"
      - run:
         command: "heroku maintenance:on --app ${HEROKU_APP_NAME}"
         name: "heroku maintenance on"
      - run:
          command: |
              docker login --username=${HEROKU_LOGIN} --password=${HROKU_AUTH_TOKEN} registry.heroku.com
              docker push registry.heroku.com/${HEROKU_APP_NAME}/web
              heroku container:push web --app ${HEROKU_APP_NAME}
              heroku container:release web --app ${HEROKU_APP_NAME}
          name: "push container to registry.heroku.com"
      - run:
          command: "heroku maintenance:off --app ${HEROKU_APP_NAME}"
          name: "heroku maintenance off"
      # - run:
      #   node/with-cache:
      #     steps:
      #       -
      #         run: "yarn install"
      #       -
      #         run: "yarn test"
# orbs:
#   node: circleci/node@1.1.6
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
             - build
